# Generated by Django 4.1.7 on 2023-04-26 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin Nombre', max_length=50)),
                ('raza', models.CharField(default='Perro', max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tel', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(default='En adopción', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images')),
                ('descripcion', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
