# Generated by Django 4.1.7 on 2023-04-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
